### ISSUE TITLE
Filetype mime

### ISSUE THREAD

**Issue by daveteu** [LarsKoelpin/magic-bytes#16]
Thank you for this package.

Have to use this package since file-type@17 changed to ESM mode and forced a lot of code change just to accommodate the package. Checking out this package proves to be a wise choice.

May I know how your pattern tree is generated and any way for us to help in updating the pattern tree?

There are a lot of file types without mime, for e.g. pdf with mime-type application/pdf but it's returning empty ''.

**Comment by LarsKoelpin** [comment]
Sure, its defined here: 

https://github.com/LarsKoelpin/magic-bytes/blob/master/src/model/pattern-tree.ts

which defines all available types.

The packcage script "gen-tree" 
`npm run gen-tree`

generates a file:
https://github.com/LarsKoelpin/magic-bytes/blob/master/src/pattern-tree.snapshot.ts

this File is beeing looked up by the logic in the end https://github.com/LarsKoelpin/magic-bytes/blob/master/src/model/tree.ts

Does this answer your question?

**Comment by daveteu** [comment]
I will throw in some common file types that I know.
