### ISSUE TITLE
mp4

### ISSUE THREAD

**Issue by DimaTrollFace** [LarsKoelpin/magic-bytes#19]
Hi. Could you please add the mime type for .mp4?

This is what I am getting now:
`[{typename: 'pic'}, {typename: 'pif'}, {typename: 'sea'}, {typename: 'ytr'}]`

Thank you!

**Comment by Tenpi** [comment]
Hi, I would like to second the support for mp4 files. 

On the same, note, `.mov` also returns the same result:
`[{typename: 'pic'}, {typename: 'pif'}, {typename: 'sea'}, {typename: 'ytr'}]`

Both `.mkv` and `.webm` return this same result so it's impossible to tell which is which (only from the file extension, which could be changed):
`[{"typename": "mkv"},{"typename": "mka"},{"typename": "mks"},{"typename": "mk3d"},{"typename": "webm","mime": "audio/webm","extension": "webm"}]`

So overall, add better support for video files.

**Comment by LarsKoelpin** [comment]
mkv, mka, mks mk3d and webm share the same signature (see: https://en.wikipedia.org/wiki/List_of_file_signatures).

mp4 shall be detected correctly now.

**Comment by DimaTrollFace** [comment]
It works. Thank you.
