### ISSUE TITLE
Issue with MKV files

### ISSUE THREAD

**Issue by nitaysol** [LarsKoelpin/magic-bytes#40]
Hi,
I'm testing 'filetypemime' functionality on '.mkv' file and it returns me an array of length 5
which contains 4 empty strings and 1 string of 'webm'(I would expect it to return 'mkv', 'mka', 'mks', 'mk3d' and 'webm' as suggested in the list of file signature).
I have tested it with two '.mkv' files.
Would appreciate you'r help in the matter unless Im doing something wrong:)
Thanks!

![image](https://github.com/LarsKoelpin/magic-bytes/assets/57482012/80043093-924c-4d38-ba2d-c848fb8b4c4f)

**Comment by LarsKoelpin** [comment]
should be fixed in 1.0.19

https://github.com/LarsKoelpin/magic-bytes/blob/master/src/model/pattern-tree.ts#L1064

let me know if it works for you
