### ISSUE TITLE
.srt & . vtt subtitle/caption file support

### ISSUE THREAD

**Issue by CanRau** [LarsKoelpin/magic-bytes#44]
Just started out with this lib and was wondering why I couldn't get it working, until I realized that `.srt` isn't yet supported 😅

Also `.vtt` for WebVTT files would be fantastic please 🙏❤️

Specs and magic numbers
[SRT](https://en.wikipedia.org/wiki/SubRip#:~:text=application/x%2Dsubrip)
[WebVTT](https://www.w3.org/TR/webvtt1/#:~:text=following%20byte%20sequences)

according to [this SO](https://stackoverflow.com/a/68893365/3484824) the mime type of .srt could be `application/x-subrip` or `application/octet-stream` tho should probably just return the former which is also named by wikipedia linked above

**Update**: tried to implement but probably have no idea what I'm doing 😅 Should I still push a PR as a starting point maybe?

**Comment by LarsKoelpin** [comment]
https://github.com/LarsKoelpin/magic-bytes/commit/7b2d560cfcca23bda4d4feca7db3684778a62bd9 let me know if it works for you.

I released version 1.4.0

You can check it here: https://larskoelpin.github.io/magic-bytes/

**Comment by CanRau** [comment]
wow that was quick thank you so much, haha the testfiles and testcases I prepared fail, but uploading another .srt I've got handy to https://larskoelpin.github.io/magic-bytes/ works 😅
might've done something wrong saving 🤔 just re-created using TextEdit instead of VSCode but same

Here's an example `a.srt` file

```srt
1
00:02:16,612 --> 00:02:19,376
Senator, we're making
our final approach into Coruscant.

2
00:02:19,482 --> 00:02:21,609
Very good, Lieutenant.

3
00:03:13,336 --> 00:03:15,167
We made it.

4
00:03:18,608 --> 00:03:20,371
I guess I was wrong.

5
00:03:20,476 --> 00:03:22,671
There was no danger at all.
```

here WebVTT `a.vtt`

```vtt
00:28.000 --> 00:30.000 position:90% align:right size:35%
...you have your robotics, and I
just want to be awesome in space.

00:31.000 --> 00:33.000 position:90% align:right size:35%
Why don't you just admit that
you're freaked out by my robot hand?
```

here my testcases

```tsx
it("detects srt", () => {
  const file = getBytes("a.srt");
  const result = filetypemime(file);
  expect(result).toContain("application/x-subrip");
});

it("detects vtt", () => {
  const file = getBytes("a.vtt");
  const result = filetypemime(file);
  expect(result).toContain("text/vtt");
});
```

**Comment by LarsKoelpin** [comment]
Yeah the magic bytes provided by the wikipedia page say

```
31 0D 0A 30 30 3A
```
which translates to

```
1↵00:
```

Where ↵ seems to be Carriage Return.

On my machine your file encodes in LF instead, which results in this:

```
╭─  ~/dev/magic-bytes/src/testfiles on  master +2 !3 ······ at 21:55:46
╰─❯ xxd -g1 a.srt 
00000000: 31 0a 30 30 3a 30 32 3a 31 36 2c 36 31 32 20 2d  1.00:02:16,612 -
```

The 0a (LF) has to be CR (OD). That's why its not working for me. I don't know if LF is actually allowed in this kind of files, as it is not listed?

**Comment by CanRau** [comment]
very interesting, I see.

Just asked Bing chat and found those

> Each record is separated by a blank line which only contains the CRLF control characters.
> — [KDS-SRT: SubRip (.SRT File Extension)](http://www.textfiles.com/uploads/kds-srt.txt#:~:text=which%20only%20contains%20the%20CRLF%20control%20characters)

> parsing the line break depends on the application. Some applications want CRLF and some only LF
> — [SRT Subtitles - issue with line breaks](https://superuser.com/questions/788972/srt-subtitles-issue-with-line-breaks)

so maybe safer to actually only accept CRLF, though I'm thinking I should try to potentially fix those on upload to normalize 🤔 

Just a curious thought, could something like the following work/be interesting?
```ts
add("SubRip", ["0x31", "0x0D", "0x0A", "0x30", "0x30", "0x3A"], {
  mime: "application/x-subrip",
  extension: "srt",
  lineBreak: "CRLF",
});

add("SubRip", ["0x31", "0x0A", "0x30", "0x30", "0x3A"], {
  mime: "application/x-subrip",
  extension: "srt",
  lineBreak: "LF",
});
```
so then my app could check if `extension === "srt"` & `lineBreak === "LF"` and then normalize to CRLF

though no idea if the second could collide with other existing file types 🤷🏼

**Comment by LarsKoelpin** [comment]
Actually I think detecting linebreaks is not the scope of this library, as it would require knowledge / parsing from the filetype itself.

Maybe a parsing function would fit, which extracts meta-data and stuff, but atm it does not exist.

Regarding your VTT file, it seems like the text file you sent me was missing the HEADER-bytes (WebVTT)

```WEBVTT

00:28.000 --> 00:30.000 position:90% align:right size:35%
...you have your robotics, and I
just want to be awesome in space.

00:31.000 --> 00:33.000 position:90% align:right size:35%
Why don't you just admit that
you're freaked out by my robot hand?
```

so this works.

**Comment by CanRau** [comment]
nice you're right, I quickly copied it from the spec page and didn't realize that this is part of it 😅 

Thank you so much for making all of this work so quickly, this is really helpful ❤️
