### ISSUE TITLE
*.hevc files support (ios video format) 

### ISSUE THREAD

**Issue by alexeyuzlov** [LarsKoelpin/magic-bytes#50]
It will be awesome to have _hevc_ file's support as well you have support of _heic_ format for images.

**Comment by LarsKoelpin** [comment]
I'm happy to add it, but I can't find any byte signature for hevc https://en.wikipedia.org/wiki/List_of_file_signatures

**Comment by alexeyuzlov** [comment]
Oh, unfortunately 😕 thanks for help, you can close the issue
