### ISSUE TITLE
Can we relax the pattern for JPGs?

### ISSUE THREAD

**Issue by pastelmind** [LarsKoelpin/magic-bytes#51]
I encountered a JPEG file with magic bytes `0xFF 0xD8 0xFF 0xE2`. The current version (1.7.0) of magic-bytes.js does not recognize this file, but my PC and Google Chrome seems to handle it fine. I also tested it against [file-type](https://github.com/sindresorhus/file-type), which correctly identified it as a JPG.

file-type accepts my JPG because it only checks the first three bytes (`0xFF 0xD8 0xFF`) to decide that a file is JPG:

https://github.com/sindresorhus/file-type/blob/37233b1c9c5c55aab4308f5c1991569dd4e414cc/core.js#L304-L316

```ts
		if (this.check([0xFF, 0xD8, 0xFF])) {
			if (this.check([0xF7], {offset: 3})) { // JPG7/SOF55, indicating a ISO/IEC 14495 / JPEG-LS file
				return {
					ext: 'jls',
					mime: 'image/jls',
				};
			}

			return {
				ext: 'jpg',
				mime: 'image/jpeg',
			};
		}
```

(technically, there is a check for JLS files, but I am unfamiliar with them)
I assume this is OK, since file-type has kept this code around for at least 3 years and no one has complained about false positives. (also see https://github.com/sindresorhus/file-type/issues/487#issuecomment-909413631)

Unfortunately, our bundler situation prevents us from using file-type. It would be great if magic-bytes.js supported my JPG as well, perhaps by relaxing the pattern for JPGs.

Can this be done? I am willing to submit a PR.

**Comment by LarsKoelpin** [comment]
acutally i noticed the pattern:
 FF D8 FF E0

seems to be missing. Does yur image fall into this category?

**Comment by pastelmind** [comment]
Nope, mine is `FF D8 FF E2`. It seems to use a proprietary segment `E2`, but image viewers seem to ignore this and display the image data.

The structure of JPG makes it difficult to generalize the fourth byte, since some programs add arbitrary segments. See https://stackoverflow.com/a/5413049

**Comment by pastelmind** [comment]
Hey, thanks for adding 2ea4e4028160e2d216703d737113a280bf28f3f2 in v1.8.0. But this addition would obsolete existing checks for JPEG, as they are now redundant:

https://github.com/LarsKoelpin/magic-bytes/blob/4beef5efca03e54bbe5b86640085347b4be62341/src/model/pattern-tree.ts#L70-L109

I expected you to remove them altogether, but you left them in. Are these still necessary? If not, I'll submit a PR to delete them.
