### ISSUE TITLE
Add support for streams

### ISSUE THREAD

**Issue by kazazor** [LarsKoelpin/magic-bytes#59]
Hi, I did not find a way to do it using the package but support for streams instead of writing the file to the disk (on NodeJS environment) would be great!
For example `file-type` package has the `fileTypeFromStream`

Does it exist and I didn't find it?

Ideally, it would be great to provide a stream in which the package will only read the magic bytes, and then reading from the stream will stop.
I want to use this package on huge files, and loading all of them to the memory/file system doesn't make sense.

**Comment by LarsKoelpin** [comment]
Actually this library does not persist any files to the disk.

You can read the stream on user-level and pipe the bytes you read into this lib. Something like this should do the trick

```
const fs = require('fs');
const mb = require("magic-bytes.js");

const fileLocation = './hello.png';
const fileStream = fs.createReadStream(fileLocation, {start: 0, end: 128}); // read the first using a stream

fileStream.on('data', (data) => {
  console.log(mb.filetypeinfo(data)) // analyse the bytes here
});
          
```

**Comment by kazazor** [comment]
Thanks @LarsKoelpin ! This looks promising.

On the library level I still believe having a dedicated function that does this magic for you could be a great interface- but that's your call :) 

Thanks again!
